from pathlib import Path
from analysis.fosters_dashboard import build_fosters_dashboard
from analysis.acwr_dashboard import build_ultra_acwr_dashboard


def generate_training_report(
    summary_path: str,
    output_html: str = "../out/training_report.html",
):
    """
    Generates a multi-section HTML training report with:
    - Foster load dashboard
    - Ultra ACWR analysis
    """

    output_path = Path(output_html)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Build figures
    fosters_fig = build_fosters_dashboard(summary_path)
    acwr_fig = build_ultra_acwr_dashboard(summary_path)

    # Convert to HTML snippets
    fosters_html = fosters_fig.to_html(full_html=False, include_plotlyjs="cdn")
    acwr_html = acwr_fig.to_html(full_html=False, include_plotlyjs=False)

    # -----------------------------
    # Compose HTML
    # -----------------------------
    html = f"""
    <html>
    <head>
        <title>Training Report</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                margin: 40px;
                background-color: #f8f9fa;
            }}
            h1, h2 {{
                color: #222;
            }}
            .section {{
                margin-bottom: 60px;
                padding: 20px;
                background: white;
                border-radius: 10px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.05);
            }}
            .explanation {{
                color: #555;
                max-width: 900px;
                line-height: 1.6;
            }}
        </style>
    </head>

    <body>

    <h1>🏃 Ultra Training Report</h1>

    <div class="section">
        <h2>1. Weekly Load & Structural Strain</h2>
        <div class="explanation">
            This chart shows how your total training load is distributed across different activity types each week.
            The stacked bars reflect the composition of your training, while the lower panel shows:
            <ul>
                <li><b>Monotony</b>: How repetitive your training is (higher = less variation)</li>
                <li><b>Strain</b>: Total weekly load adjusted for monotony</li>
            </ul>
            Sustained high monotony (&gt;2.0) combined with high strain is a known injury risk pattern.
        </div>
        {fosters_html}
    </div>

    <div class="section">
        <h2>2. Ultra-Endurance ACWR (7:56 EWMA)</h2>
        <div class="explanation">
            This chart tracks the relationship between short-term fatigue and long-term fitness:
            <ul>
                <li><b>Acute Load (7d)</b>: Recent fatigue</li>
                <li><b>Chronic Load (56d)</b>: Long-term fitness base</li>
                <li><b>ACWR</b>: Ratio of acute to chronic load</li>
            </ul>

            <b>Interpretation:</b>
            <ul>
                <li>0.8 – 1.3 → Optimal training zone</li>
                <li>&gt;1.5 → Increased injury / overreach risk</li>
            </ul>

            This ultra-endurance version uses a longer (56-day) chronic window to better reflect marathon and ultra adaptations.
        </div>
        {acwr_html}
    </div>

    </body>
    </html>
    """

    output_path.write_text(html)
    print(f"Report generated: {output_path}")

if __name__ == "__main__":
    # Ensure this points to the summary file generated by your previous script
    generate_training_report("master_workout_summary.tsv")