import pandas as pd
from pathlib import Path
import plotly.graph_objects as go
from plotly.subplots import make_subplots


def build_fosters_dashboard(summary_tsv_path: str) -> go.Figure:
    """
    Builds an interactive Plotly dashboard for:
    - Weekly stacked training load
    - Daily monotony + strain

    Returns:
        plotly.graph_objects.Figure
    """
    if not Path(summary_tsv_path).exists():
        raise FileNotFoundError(f"{summary_tsv_path} not found")

    # -----------------------------
    # Load & Prepare
    # -----------------------------
    df = pd.read_csv(summary_tsv_path, sep="\t")
    df["date"] = pd.to_datetime(df["date"])

    df["sub_sport"] = df["sub_sport"].fillna("generic")
    df["avg_hr"] = df["avg_hr"].fillna(100)

    df["load_score"] = (df["duration_min"] * df["avg_hr"]) / 100
    df["activity_key"] = df["sport"].astype(str) + " | " + df["sub_sport"].astype(str)

    # -----------------------------
    # Daily pivot
    # -----------------------------
    daily_pivot = (
        df.pivot_table(
            index="date",
            columns="activity_key",
            values="load_score",
            aggfunc="sum",
        )
        .resample("D")
        .sum()
        .fillna(0)
    )

    total_daily_load = daily_pivot.sum(axis=1)

    rolling_mean = total_daily_load.rolling(7).mean()
    rolling_std = total_daily_load.rolling(7).std()

    monotony = rolling_mean / (rolling_std + 1e-3)
    weekly_sum = total_daily_load.rolling(7).sum()
    strain = weekly_sum * monotony

    # -----------------------------
    # Weekly aggregation
    # -----------------------------
    weekly_pivot = daily_pivot.resample("W").sum()

    counts = df["activity_key"].value_counts()
    weekly_pivot = weekly_pivot[counts.index.tolist()]

    # -----------------------------
    # Build Plotly Figure
    # -----------------------------
    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.08,
        row_heights=[0.6, 0.4],
        specs=[[{"type": "bar"}], [{"secondary_y": True}]],
    )

    # -----------------------------
    # TOP: Weekly stacked bars
    # -----------------------------
    for col in weekly_pivot.columns:
        fig.add_trace(
            go.Bar(
                x=weekly_pivot.index,
                y=weekly_pivot[col],
                name=f"{col} (n={counts[col]})",
            ),
            row=1,
            col=1,
        )

    # -----------------------------
    # BOTTOM: Monotony + Strain
    # -----------------------------
    fig.add_trace(
        go.Scatter(
            x=daily_pivot.index,
            y=monotony,
            name="Monotony",
            fill="tozeroy",
            opacity=0.3,
        ),
        row=2,
        col=1,
        secondary_y=False,
    )

    fig.add_trace(
        go.Scatter(
            x=daily_pivot.index,
            y=strain,
            name="Strain",
            line=dict(width=2),
        ),
        row=2,
        col=1,
        secondary_y=True,
    )

    # Danger line
    fig.add_hline(
        y=2.0,
        line_dash="dash",
        row=2,
        col=1,
        annotation_text="Monotony Danger",
    )

    # Burn-in shading (first 28 days)
    if len(daily_pivot) > 0:
        start = daily_pivot.index[0]
        end = daily_pivot.index[min(27, len(daily_pivot) - 1)]

        fig.add_vrect(
            x0=start,
            x1=end,
            fillcolor="white",
            opacity=0.6,
            layer="above",
            line_width=0,
            annotation_text="Model Burn-in",
            row=2,
            col=1,
        )

    # -----------------------------
    # Layout
    # -----------------------------
    fig.update_layout(
        title="Ultra Training Analysis: Load & Structural Strain",
        barmode="stack",
        height=800,
        legend=dict(orientation="h"),
    )

    fig.update_yaxes(title_text="Weekly Load (TRIMP)", row=1, col=1)
    fig.update_yaxes(title_text="Monotony", row=2, col=1, secondary_y=False)
    fig.update_yaxes(title_text="Strain", row=2, col=1, secondary_y=True)

    return fig

if __name__ == "__main__":
    # Ensure this points to the summary file generated by your previous script
    build_fosters_dashboard("master_workout_summary.tsv")